language: python
python: "2.7"
env: LIBGIT2=~/libgit2-0.20.0/_install/ LD_LIBRARY_PATH=~/libgit2-0.20.0/_install/lib

before_install:
  - sudo apt-get install cmake
  - cd ~
  - wget https://github.com/libgit2/libgit2/archive/v0.20.0.tar.gz
  - tar -xf v0.20.0.tar.gz
  - cd libgit2-0.20.0
  - mkdir build && cd $_
  - cmake .. -DCMAKE_INSTALL_PREFIX=../_install -DBUILD_CLAR=OFF
  - cmake --build . --target install

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - nose2
