language: python
python: "2.7"
env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

before_install:
  - ./libgit2.sh

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - nose2
